import * as React from 'react';
import { styled } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Paper from '@mui/material/Paper';
import Fab from '@mui/material/Fab';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import ListSubheader from '@mui/material/ListSubheader';
import Avatar from '@mui/material/Avatar';
import { auth, db } from '@src/firebase/firebaseConfigs';
import { useAuthState } from 'react-firebase-hooks/auth'
import { useConversation } from "hooks/useConversation";
import { useRouter } from 'next/router';

const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/static/images/avatar/5.jpg',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
    },
];
export default function BottomAppBar() {
    const router = useRouter()
    const [loggedInUser, _loading, _error] = useAuthState(auth)
    const { conversations } = useConversation()

    return (
        <React.Fragment>
            <CssBaseline />
            <Paper>
                <List sx={{
                    mb: 2,
                    width: '100%',
                    bgcolor: 'background.paper',
                    position: 'relative',
                    overflow: 'auto',
                    maxHeight: 475,
                    '& ul': { padding: 0 }
                }}>

                    {conversations?.map((con, index) => {

                        const receiverEmail = con.users.filter(i => i !== loggedInUser?.email)
                        return (<ListItem button onClick={() => router.push('/messenger/' + con.id)} key={index}>
                            <ListItemAvatar>
                                <Avatar alt="Profile Picture" src="" />
                            </ListItemAvatar>
                            <ListItemText primary={receiverEmail[0]} secondary={"chu text"} />
                        </ListItem>)

                    })}

                    {messages.map(({ id, primary, secondary, person }) => (
                        <React.Fragment key={id}>
                            {id === 1 && (
                                <ListSubheader>
                                    Today
                                </ListSubheader>
                            )}
                            {id === 3 && (
                                <ListSubheader >
                                    Yesterday
                                </ListSubheader>
                            )}
                            <ListItem button>
                                <ListItemAvatar>
                                    <Avatar alt="Profile Picture" src={person} />
                                </ListItemAvatar>
                                <ListItemText primary={primary} secondary={secondary} />
                            </ListItem>
                        </React.Fragment>
                    ))}
                </List>
            </Paper>
        </React.Fragment>
    );
}